### ISSUE TITLE
Real time Multiplayer with websocket page

### ISSUE THREAD

**Issue by Chris5613** [Chris5613/RankRiddler#102]
Using Socket.io implement a live multiplayer 1 on 1 feature.

**Comment by milan-lakhani** [comment]
Hey @Chris5613  if you could break this Issue into multiple small ones maybe I can help. I have some experience with socket.io.

**Comment by Chris5613** [comment]
@milan-lakhani will do. I'm having trouble with it so I'll throw some issues up in a bit
