### ISSUE TITLE
Create the main Multiplayer Page on the client

### ISSUE THREAD

**Issue by Chris5613** [Chris5613/RankRiddler#108]
![245d6a61d783978121cebab2aaf80fec](https://github.com/Chris5613/RankRiddler/assets/24240227/babf630b-1681-4e87-a359-df41afe570e8)

These are the two designs I thought of for the main multiplayer page.

Either we let users join a queue and they'll be matched off of that or let them create a room and let other users join them.
Up to you which design you want to pick or your own design if you want to.

Make sure you link the page to the navbar and in app.js to react-router

**Comment by Shubh8899** [comment]
I would like to work on this.

**Comment by Chris5613** [comment]
@Shubh8899 Assigned. When you submit the pull request. Please merge it in to test-branch

**Comment by ynzulak** [comment]
can i work on this?

**Comment by Shubh8899** [comment]
@Chris5613  created new PR to merge in test-branch, please review.
