### ISSUE TITLE
Track Wins and Losses from multiplayer

### ISSUE THREAD

**Issue by Chris5613** [Chris5613/RankRiddler#111]
For this new multiplayer feature, I would like to track a user's wins and losses. 

You could just add a win and losses properties to the user model in the backend and create 2 endpoints one for if a user wins and one for if they lose.

**Comment by milan-lakhani** [comment]
@Chris5613 I can take this one.

**Comment by Chris5613** [comment]
@milan-lakhani when you're merging please merge it into the test-branch not main.

**Comment by Chris5613** [comment]
@milan-lakhani Hey what's your progress?

**Comment by milan-lakhani** [comment]
@Chris5613 sorry, I have been jammed this past week, let me take on this issue this weekend. Thanks :)
