### ISSUE TITLE
New Navbar Needed

### ISSUE THREAD

**Issue by Chris5613** [Chris5613/RankRiddler#125]
The current Navbar isn't really the best so probably time for an updated one plus new media queries to make it better on mobile screens.

**Comment by SD191100** [comment]
hello, can I contribute to your web app?.. I am new to programming and trying to learn new things as well as starting my contributions with your app

**Comment by ynzulak** [comment]
Hello, can i work on this issue?

**Comment by Chris5613** [comment]
@SD191100 @ynzulak I'll assign both of you and I'll choose the best looking nav

**Comment by ynzulak** [comment]
@Chris5613 Im currently working on your nav. Do you want something special?

**Comment by Chris5613** [comment]
@ynzulak What you do is entirely up to you, just as long as it fits the site theme
