### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by Chris5613** [Chris5613/RankRiddler#54]
Need to clean up some of the code and delete some of the unused css classes or code that is not needed.

**Comment by Chris5613** [comment]
@loshjarson assigned!

**Comment by loshjarson** [comment]
Is the "auth" back-end controller part of an authentication update in the works or a previous authentication method that is no longer needed?

**Comment by Chris5613** [comment]
It is currently not being used but it is for a different issue that is currently up and not finished. Issue #55
