### ISSUE TITLE
Protecting the endpoints on the backend (Node.js)

### ISSUE THREAD

**Issue by Chris5613** [Chris5613/RankRiddler#55]
Currently on the backend, I have an auth.js file that has an endpoint that checks if a user is authorized to make an API call to the server.

Endpoints should be protected so no one not logged in or users who don't have a token can use it.
I've tried a few ways but I'm currently not able to implement it currently. 

I believe you just have to add the auth to each endpoint in the router and then in the frontend, you would get the token from cookies and include it in the headers, could be wrong.

**Comment by ksharma20** [comment]
Can I pick this one?

**Comment by Chris5613** [comment]
@ksharma20 Hey so the auth file got deleted in a merge but what you could do is make a new auth file and protect the current endpoints that we have right now. 

You would need to run the code to create a token when a user creates a username in the setting.jsx page then store it in to cookies and any api call will include the token.

**Comment by Chris5613** [comment]
Going to be closing this issue. This is no longer needed.
