### ISSUE TITLE
Username creation validation

### ISSUE THREAD

**Issue by Chris5613** [Chris5613/RankRiddler#56]
I want some sort of a validation system for the signup process to prevent anyone from making a username that's racist or means.

An error should pop up like an alert() or a message under the form telling the user, they can't use or create an account with that username. We could possibly use a third-party application for this, which could be faster than coding it ourselves.

**Comment by loshjarson** [comment]
I can work on finding a solution to this

**Comment by Chris5613** [comment]
@loshjarson  assigned.

**Comment by Chris5613** [comment]
@loshjarson I revamped the whole user stuff so there's no longer any signup/login/logout feature all user info will now be saved to cookies and saved to the database via a settings page.

What could be done is within the settings page there's a one-time username reset, which users can do and you can put the validation there instead of the signup.

**Comment by loshjarson** [comment]
> @loshjarson I revamped the whole user stuff so there's no longer any signup/login/logout feature all user info will now be saved to cookies and saved to the database via a settings page.
> 
> What could be done is within the settings page there's a one-time username reset, which users can do and you can put the validation there instead of the signup.

@Chris5613 alrighty, sounds good. I will take a look at it.

**Comment by loshjarson** [comment]
@Chris5613 Im not really seeing a need for validation here especially with no passwords or tokens being used with the update. I am all ears for your ideas though

**Comment by Chris5613** [comment]
@loshjarson One of my ideas was to use the npm package " npm bad-words" 

https://www.npmjs.com/package/bad-words

and from that, you add a check to see if the username being made is in there if there is then stop it.
I already have a checkUsername in there to check for other stuff but you might be able to add to it. 
If a badword is found you can just do prompt() and state that they can't use that name.

Another way was to create a list and manually write a bunch of bad words then filter it with that but let me know what you think. I had a few accounts that were created with the n word or other bad words and I would like to stop those.

**Comment by loshjarson** [comment]
@Chris5613 I have also been looking at that library and think it would be the best bet.

 I will start implementing and testing it asap to stop those

**Comment by Chris5613** [comment]
@loshjarson I would say do whatever you think will work and if it works then we're good. 

How you implement it is entirely up to you!
