### ISSUE TITLE
Folder redesign

### ISSUE THREAD

**Issue by Chris5613** [Chris5613/RankRiddler#68]
This is a pretty good first issue for anybody who wants to do their first.

Just reorganize all the component files into different folders that match the overall section.

For example, you can put the TOS.jsx and Privacy.jsx files together in a folder called "legal" or whatever fits.
Up to you!

Comment below to be assigned.

**Comment by ksharma20** [comment]
I can pick this up!

**Comment by lokytech5** [comment]
interested

**Comment by Chris5613** [comment]
@lokytech5 I will assign you sine ksharma is already working on a issue :)

**Comment by lokytech5** [comment]
okay.

**Comment by lokytech5** [comment]
If  there are other things you need to handle within your projects, just know am ready. The game application is nice
