### ISSUE TITLE
Encrypt or make it harder for users to mess with cookies

### ISSUE THREAD

**Issue by Chris5613** [Chris5613/RankRiddler#71]
Currently, The cookies that hold most of the data are easily edited by any user.

I had someone with 1000 points this morning which I had to delete, We need to either encrypt it from the server side or instead of setting the cookies in the front end we can do it server-side and set it to httpONLY which will be designed to be inaccessible to JavaScript, so they cannot be modified or accessed by client-side code so only API calls can edit it which will require a lot of code changes to the backend.

Opened to ideas

**Comment by Chris5613** [comment]
@nazrul7711 would you have the knowledge to work on this?

**Comment by nazrul7711** [comment]
i will try @Chris5613

**Comment by Chris5613** [comment]
@nazrul7711  Hey any updates? I know this is a pretty hard issue I've been having alot of trouble figuring it out myself.

**Comment by nazrul7711** [comment]
@Chris5613 I haven't started working on it . I was busy with something else. I will start working on it today

**Comment by Chris5613** [comment]
@nazrul7711 Hey you no longer need to work on this issue. I solved it, I deleted the cookies and moved it on to the server side so users can't mess with it.
