### ISSUE TITLE
Report Video Button

### ISSUE THREAD

**Issue by Chris5613** [Chris5613/RankRiddler#80]
For each one of the game pages, I want a report video button somewhere that will send a POST request to the database.

The request should give the full youtube link and either rank or player info.
You could use the bug endpoint for this which is:

```
https://rr-back-end.onrender.com/form/bug
```
or you could create your own endpoint on the backend with Node. 

You could just link the bug page to the button or do something creative. 
Just don't create a new page.

**Comment by milan-lakhani** [comment]
Hello @Chris5613 , I would like to take on this issue. I am new to contributing open source, so please correct me anywhere necessary during the process.

**Comment by Chris5613** [comment]
@milan-lakhani  Welcome! free feel to work on it ill assign you. When you're ready submit a pull request.

**Comment by milan-lakhani** [comment]
Hey @Chris5613 , I have created a new pull request #85 for the functionality. Please let me know what you think! Thanks.
