### ISSUE TITLE
Add a 404 Page

### ISSUE THREAD

**Issue by Sukhendu2002** [Chris5613/RankRiddler#93]

**Comment by Chris5613** [comment]
@Aryan123-rgb run npm install first in the front-end folder to install all the stuff needed then run npm start

**Comment by Aryan123-rgb** [comment]
@Chris5613 But tell me ,does this command -> "npm run dev" often takes too long . I was similar issues when I was try to setup another project locally

**Comment by Chris5613** [comment]
@Aryan123-rgb I am unsure why but I would just use npm start its easier

**Comment by Aryan123-rgb** [comment]
@Chris5613 You are right but they mentioned it in their .md file . That's why I was asking . Anyway thanks for your help

**Comment by Aryan123-rgb** [comment]
@Chris5613  I think I can fix this issue . Here's the solution :-
I can add this <Route component={Error} /> in App.js file and then I can add this component (Error.jsx) in components folder . So the browser will be automatically directed the error page if none of the above route page is loaded . If the approach is correct please assign this issue to me

**Comment by Aryan123-rgb** [comment]
@Chris5613  cool :)

**Comment by Aryan123-rgb** [comment]
@Chris5613 I have created a pull request . Please review it and notify me if any necessary changes are required :).  

Thank you
