### ISSUE TITLE
Add some validation for clip submission

### ISSUE THREAD

**Issue by Chris5613** [Chris5613/RankRiddler#96]
Currently, when a user submits a clip they're able to submit the same clip over and over which prompted a troll user to spam the same video 200 times.

I would like some validation where it checks if the youtube url is already in the database and if it is a alert() should pop up to stop it.

**Comment by milan-lakhani** [comment]
I can take up on that issue @Chris5613

**Comment by milan-lakhani** [comment]
Please assign it to me and I will start working on it! Thanks!
